# -*- coding: utf-8 -*-
"""aus_univar.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NJISWbb3v3gshlEEHBu-YFAEJVdpfMi1

# **Univariate Forecasting**

https://huggingface.co/amazon/chronos-2
"""

# !pip install git+https://github.com/amazon-science/chronos-forecasting.git
import pandas as pd  # requires: pip install 'pandas[pyarrow]'
import numpy as np
from chronos import Chronos2Pipeline

# 1. Load the official Chronos-2 pipeline
pipeline = Chronos2Pipeline.from_pretrained("amazon/chronos-2", device_map="cuda" if torch.cuda.is_available() else "cpu")

# 2. Load the intermediate processed data
context_df = pd.read_csv("context_df.csv")
ground_truth = np.load("horizon_true.npy")
# print(context_df)
# print(ground_truth)

# Ensure the timestamp column is parsed as datetime objects for the API
context_df["timestamp"] = pd.to_datetime(context_df["timestamp"])

# 3. Generate predictions
pred_df = pipeline.predict_df(
    context_df,
    prediction_length=24,  # Number of steps (hours) to forecast
    quantile_levels=[0.1, 0.5, 0.9],  # Quantiles for probabilistic forecast
    id_column="id",  # Column identifying different time series
    timestamp_column="timestamp",  # Column with datetime information
    target="target",  # Column(s) with time series values to predict
)

print(pred_df)

# 4. Extract the Median Predictions
forecast_median = pred_df["0.5"].values # Or equivalently: pred_df["predictions"].values

# 5. Define Evaluation Metrics
def calculate_metrics(y_true, y_pred):
    y_true, y_pred = np.array(y_true), np.array(y_pred)

    # Root Mean Squared Error
    rmse = np.sqrt(np.mean((y_true - y_pred) ** 2))

    # Mean Absolute Percentage Error
    mape = np.mean(np.abs((y_true - y_pred) / y_true)) * 100

    return rmse, mape

# 6. Run Evaluation
rmse_score, mape_score = calculate_metrics(ground_truth, forecast_median)

print("--- Chronos-2 Univariate Baseline Metrics ---")
print(f"Ground Truth Shape: {ground_truth.shape}")  # Outputs: (24,)
print(f"Forecast Shape:     {forecast_median.shape}")  # Outputs: (24,)
print(f"RMSE: {rmse_score:.4f} MW")
print(f"MAPE: {mape_score:.4f}%")